POST http://localhost:3000/cars
Content-Type: application/json

{
"name":"Prisma",
"marca":"Chevrolet",
"ano_fabri":"2019",
"descricao":"Eficiente, oferece uma experiência bem melhor de condução do que a dos concorrentes com câmbio automatizado."

}

