version: "3.3"

services:

  backend:
    build: ./backend
    image: passoz/challenge-b2u-backend:v1
    environment:
      - ENV=${ENV}
    depends_on:
      - postgres
    ports:
      - 3000:3000

  frontend:
    build: 
      context: ./frontend
      args: 
        - REACT_APP_BACKEND_HOST=${REACT_APP_BACKEND_HOST}
    image: passoz/challenge-b2u-frontend:v1
    environment:
      - ENV="production"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - postgres
    volumes:
      - caddy-data-vol:/data
      - caddy-config-vol:/config


  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
    - pg-vol:/var/lib/postgresql/data
    ports:
    - 5432:5432

volumes:
  pg-vol:
  caddy-data-vol:
  caddy-config-vol:
