version: "3.9"
services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-bitcoin-2-u
    ports:
      - "5173:5173"

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cars
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped


  prisma-postgres-api:
    stdin_open: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: prisma-postgres-api
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    restart: always

volumes:
  postgres-data: