version: '3.4'

services:

  api-ts:
    build: 
      context: .
      target: development
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    depends_on:
      - mongo
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  mongo:
    image: mongo:4.4.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db
  
  
      
volumes:
  mongo-db: