version: '3.4'

services:

  api-ts:
    build: 
      context: .
      target: development
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
  
  

  